/* groovylint-disable CompileStatic, DuplicateStringLiteral, LineLength */
pipeline {
    agent any
    stages {
        stage('Unit Testing') {
            steps {
                sh 'python3 ./src/backend/autenticacion/login/test.py'
                sh 'python3 ./src/backend/usuario/crear/test.py'
                sh 'python3 ./src/backend/usuario/editar/test.py'
                sh 'python3 ./src/backend/usuario/eliminar/test.py'
                sh 'python3 ./src/backend/usuario/obtener/test.py'
                sh 'python3 ./src/backend/libro/crear/test.py'
                sh 'python3 ./src/backend/libro/editar/test.py'
                sh 'python3 ./src/backend/libro/eliminar/test.py'
                sh 'python3 ./src/backend/libro/obtener/test.py'
                sh 'python3 ./src/backend/orden/crear/test.py'
                sh 'python3 ./src/backend/orden/editar/test.py'
                sh 'python3 ./src/backend/orden/eliminar/test.py'
                sh 'python3 ./src/backend/orden/obtener/test.py'
            }
        }
        stage('Building') {
            steps {
                echo 'Building autentication microservices ...'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_login:latest ./src/backend/autenticacion/login/'
                echo 'Building book microservices ...'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_libro_crear:latest ./src/backend/libro/crear/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_libro_editar:latest ./src/backend/libro/editar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_libro_eliminar:latest ./src/backend/libro/eliminar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_libro_obtener:latest ./src/backend/libro/obtener/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_libro_solicitar:latest ./src/backend/libro/solicitar/'
                echo 'Building order microservices ...'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_orden_crear:latest ./src/backend/orden/crear/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_orden_editar:latest ./src/backend/orden/editar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_orden_eliminar:latest ./src/backend/orden/eliminar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_orden_obtener:latest ./src/backend/orden/obtener/'
                echo 'Building user microservices ...'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_usuario_crear:latest ./src/backend/usuario/crear/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_usuario_editar:latest ./src/backend/usuario/editar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_usuario_eliminar:latest ./src/backend/usuario/eliminar/'
                sh 'docker build --force-rm --no-cache --tag gpeitzner/ezread_usuario_obtener:latest ./src/backend/usuario/obtener/'
                echo 'Building web page ...'
                withCredentials([file(credentialsId: 'FRONTEND_TEST', variable: 'MY_FRONTEND_TEST')]) {
                    sh 'cp $MY_FRONTEND_TEST ./src/frontend/.env.test'
                    sh 'docker build --force-rm --no-cache --build-arg NODE_ENV=test --tag gpeitzner/ezread_ui:latest ./src/frontend/'
                    sh 'rm ./src/frontend/.env.test'
                }
                echo 'Cleaning intermediate building images ...'
                sh 'docker image prune -f'
            }
        }
        stage('Integration Testing') {
            steps {
                echo 'Starting tests ...'
                withCredentials([file(credentialsId: 'BACKEND_TEST', variable: 'MY_BACKEND_TEST')]) {
                    sh 'cp $MY_BACKEND_TEST ./e2e/.env-test'
                    sh 'docker-compose -f ./e2e/docker-compose-test.yml up -d'
                    echo 'Connect to http://test.ezread.ml:7900/ to view the tests'
                    sh 'sleep 30'
                    echo 'Executing e2e tests ...'
                    echo 'Running test 1 ...'
                    sh 'python3 ./e2e/test1.py'
                    echo 'Running test 2 ...'
                    sh 'python3 ./e2e/test2.py'
                    echo 'Running test 3 ...'
                    sh 'python3 ./e2e/test3.py'
                    echo 'Running test 4 ...'
                    sh 'python3 ./e2e/test4.py'
                    echo 'Running test 5 ...'
                    sh 'python3 ./e2e/test5.py'
                    echo 'Running test 6 ...'
                    sh 'python3 ./e2e/test6.py'
                    echo 'Running test 7 ...'
                    sh 'python3 ./e2e/test7.py'
                    echo 'Running test 8 ...'
                    sh 'python3 ./e2e/test8.py'
                    sh 'sleep 10'
                    sh 'docker-compose -f ./e2e/docker-compose-test.yml down'
                    sh 'sleep 10'
                    sh 'rm ./e2e/.env-test'
                    echo ':]'
                }
            }
        }
    }
}
