/* groovylint-disable CompileStatic, DuplicateStringLiteral, LineLength */
pipeline {
    agent any
    environment {
        CD_HOST     = credentials('CD_HOST')
    }
    stages {
        stage('Deploying') {
            steps {
                echo 'Deploying....'
                echo 'Building web page ...'
                withCredentials([file(credentialsId: 'FRONTEND_PROD', variable: 'MY_FRONTEND_PROD')]) {
                    sh 'cp $MY_FRONTEND_PROD ./src/frontend/.env.prod'
                    sh 'docker build --force-rm --no-cache --build-arg NODE_ENV=prod --tag gpeitzner/ezread_ui:latest ./src/frontend/'
                    sh 'rm ./src/frontend/.env.prod'
                }
                echo 'Cleaning intermediate building images ...'
                sh 'docker image prune -f'
                echo 'Pushing images to docker registry ...'
                sh 'docker push gpeitzner/ezread_login:latest'
                sh 'docker push gpeitzner/ezread_libro_crear:latest'
                sh 'docker push gpeitzner/ezread_libro_editar:latest'
                sh 'docker push gpeitzner/ezread_libro_eliminar:latest'
                sh 'docker push gpeitzner/ezread_libro_obtener:latest'
                sh 'docker push gpeitzner/ezread_orden_crear:latest'
                sh 'docker push gpeitzner/ezread_orden_editar:latest'
                sh 'docker push gpeitzner/ezread_orden_eliminar:latest'
                sh 'docker push gpeitzner/ezread_orden_obtener:latest'
                sh 'docker push gpeitzner/ezread_usuario_crear:latest'
                sh 'docker push gpeitzner/ezread_usuario_editar:latest'
                sh 'docker push gpeitzner/ezread_usuario_eliminar:latest'
                sh 'docker push gpeitzner/ezread_usuario_obtener:latest'
                sh 'docker push gpeitzner/ezread_ui:latest'
                withCredentials([file(credentialsId: 'BACKEND_PROD', variable: 'MY_BACKEND_PROD')]) {
                    sh 'cp $MY_BACKEND_PROD ./.env-prod'
                    sh 'python3 ./dev_ops/cd/deploy.py'
                    sh 'rm ./.env-prod'
                }
            }
        }
    }
}
